// Version information (production)
const DEFAULT_VERSION = 'v2.2.13';
const DEFAULT_DATE = 'May 05, 2026';

// Export constants initially with default values
export let APP_VERSION = DEFAULT_VERSION;
export let RELEASE_DATE = DEFAULT_DATE;

// NOTE: Keep only last 15 versions to prevent git overload (following Next.js pattern)
// Full history available in GitHub releases and git commits
export let VERSION_HISTORY: Array<{ version: string; date: string; changes: string[] }> = [
  {
    version: 'v2.2.13',
    date: 'May 05, 2026',
    changes: [
      'brand-setup: Meta Ads framing reversed — Windsor.ai with Meta Ads (Facebook Ads) connected is now the MANDATORY universal path for every brand (because Meta Ads MCP rollout cannot be guaranteed); the Meta Ads MCP at https://mcp.facebook.com/ads is an optional enhancement that flips downstream behavior only when explicitly opted into',
      'brand-setup: Step 2 prereq table — Windsor.ai marked *(required)* and now lists Google Ads + GA4 + Meta Ads as a combined required scope; Meta Ads MCP marked *(optional enhancement — limited rollout)* with explicit "skip without prejudice" wording',
      'brand-setup: Step 7c — Meta Ads section rewritten so Windsor.ai is the standard path and the MCP is the optional layer-on-top; user prompt for the MCP starts with "(Optional)" and reassures the user that skipping costs nothing because Windsor already covers Meta fully',
      'brand-setup: Step 7c Windsor.ai walkthrough — step 2 unconditionally instructs the user to connect Google Ads, GA4, AND Meta Ads in Windsor (no env-var conditional); Meta in Windsor is required regardless of MCP status',
      'brand-setup: Step 7c — META_ADS_SOURCE env var contract: only set to "meta_ads_mcp" when user successfully added the optional MCP; left unset otherwise (skills default to Windsor)',
      'brand-setup: Step 8 #14 — Windsor.ai test now verifies all three required connectors (Google Ads, GA4, Facebook); fails ❌ if any is missing (no partial pass). #15 Meta Ads MCP — only runs when META_ADS_SOURCE=meta_ads_mcp; skipped (not failed) otherwise since Windsor already covers Meta',
      'brand-setup: Step 8 summary table + Step 9 JSON payload — Windsor.ai row is ✅/❌ only (no skip option), Meta Ads MCP row remains ✅/❌/⏭ with notes clarifying it is purely additive',
      'digital-marketing-analyst: Phase 2 Step 1 + Weekly Step 1b — Windsor.ai with source: "facebook" is the documented default path; Meta Ads MCP is the opt-in alternative with automatic fallback to Windsor on runtime error',
      'digital-marketing-analyst: Windsor field set verified live against Windsor get_fields(connector: "facebook") which exposes 741 fields. Field map covers campaign + adset_name/adset_id/adset_effective_status + ad_name/ad_id + clicks/impressions/ctr/spend/reach/frequency/cpm/cpc + actions_landing_page_view + actions_video_view + brand-funnel-specific actions_* conversion field — near-parity with Marketing API',
      'digital-marketing-analyst: removed false claims that Windsor Facebook is "campaign-level only" and "no conversion data available" (those claims dated to a pre-2026 Windsor API and were inaccurate)',
      'digital-marketing-analyst: meta_ads JSON block — added required "source" field ("windsor" | "meta_ads_mcp") so the dashboard can interpret which field-name space the data came from. On MCP→Windsor runtime fallback, source records the data actually used (windsor), not the path attempted first',
      'data-analysis: Step 1a — same default-Windsor / opt-in-MCP branching with explicit Windsor field map and conversion-event guidance from brands/{brand}/funnel.md; corrected Windsor capability claims',
      'agents/link.md: MCP Connectors list — Windsor.ai marked required (Google Ads + GA4 + Meta Ads); Meta Ads MCP marked optional enhancement with the META_ADS_SOURCE contract documented',
    ],
  },
  {
    version: 'v2.2.12',
    date: 'May 04, 2026',
    changes: [
      'brand-setup: Step 7b — explicit instruction to save DEFAULT_BRAND (active brand slug) and {BRAND}_NOTION_DB (Notion Social Calendar DB page ID) to .claude/settings.local.json env block; how-to-get-Notion-DB-ID note included',
      'brand-setup: Step 8d — new mandatory validation block (#18, #19) that checks DEFAULT_BRAND and {BRAND}_NOTION_DB are present in settings.local.json; both are non-skippable (❌ stops the flow)',
      'brand-setup: Step 8 summary table and Step 9 completion-email connections[] now include the two env-var checks; Step 9 Slack message integration count bumped 16 → 18',
      'brand-setup: Step 10b CLAUDE.md template — replaced "Active Brand" section with "Workspace Defaults" that hardcodes the brand slug and Notion DB ID inline (so any session sees them immediately) with an env-var fallback rule for stale/copied workspaces; placeholder list extended to {brand} / {BRAND} / {notion_db_id}',
      'brand-setup: normalized {BRAND} env-var prefix convention (uppercased, hyphens removed) across Step 7b note, Step 8d, Step 8 summary, Step 9 connections, Step 10b template — replaces accidental {BRAND_UPPER} variants',
    ],
  },
  {
    version: 'v2.2.11',
    date: 'May 04, 2026',
    changes: [
      'brand-setup: Step 10 — CLAUDE.md now embeds the full content of agents/link.md directly (frontmatter stripped) instead of writing an absolute-path reference; workspace becomes self-contained for scheduled runs and fresh clones',
      'brand-setup: Step 10b uses BEGIN/END markers (<!-- BEGIN agents/link.md (embedded by brand-setup) -->) for idempotent re-runs; backwards-compat handling replaces older absolute-path Agent Identity blocks',
      'brand-setup: Meta Ads — added official Meta Ads MCP custom connector (https://mcp.facebook.com/ads); replaces Windsor.ai for Meta Ads (Facebook + Instagram) campaign data across Step 2 prereqs, Step 7c connector flow, Step 8 validation, Step 8 summary table, Step 9 completion email JSON',
      'brand-setup: Windsor.ai narrowed to Google Ads + GA4 only; vault-storage note in Step 7b clarifies Meta Ads credentials live with the Meta Ads MCP, not Windsor; integration count bumped 15 → 16 in Step 9 Slack message',
      'digital-marketing-analyst: Phase 2 daily Meta pull and Weekly Step 1b migrated from Windsor.ai (source: "facebook") to the Meta Ads MCP; ad_set / ad / lp_views / video_views / conversions / cpm now expected (Meta Marketing API surfaces them); Notes data-sources / data-lag / TikTok-future updated; lp_views note no longer says "not in Windsor"',
      'data-analysis: Step 1a split — Windsor.ai block for Google Ads + GA4, separate Meta Ads MCP block for Facebook + Instagram; inputs table data-source row updated; fallback prompt mentions both connectors',
      'agents/link.md: MCP Connectors list — Windsor.ai narrowed to Google Ads + GA4; new Meta Ads MCP custom-connector entry',
    ],
  },
  {
    version: 'v2.2.10',
    date: 'May 04, 2026',
    changes: [
      'brand-setup: Step 4b (mandatory) — Claude Design system installed at brands/{brand}/design-system/ via claude.ai/design Share → Download Project as .zip',
      'brand-setup: Step 4c (optional) — Social Carousel (4:5) and Social Story (9:16) Claude Design templates installed at brands/{brand}/social-carousel-template/ and social-story-template/',
      'brand-setup: prerequisites overview, directory structure, and Step 9 completion email updated to include design-system + template folders',
      'brand-setup: Step 10a hardened to enforce ABSOLUTE path for agents/link.md — os.path.abspath(os.path.realpath(...)) + os.path.isabs assertion, manual-fallback path is also normalized and validated',
      'brand-setup: Step 10b explicit instruction that link.md path written into CLAUDE.md must be absolute (verbatim with drive letter on Windows / leading slash on Unix)',
      'agents/link.md: design-system/ added to Context Files as authoritative for visuals; carousel/story templates listed as optional with fallback; new Visual consistency rule',
      'creative-designer: design-system/ is source of truth (replaces brand.md as primary visual reference); new Step 4a branches Carousel/Story to template-render via Playwright when template folder exists; Gemini still required to fill visual slots inside template',
      'content-generator: Step 2 reads design-system/ (mandatory) + detects optional templates; Step 4c-template renders via Playwright for IG/FB Carousel/Story when templates installed; falls back to Gemini+Pillow if templates absent or Playwright fails; quality checklist guards against double-stamp text/logo on template path',
      'content-creation: reads design-system/ to size copy against text frames; for IG/FB carousel/story copy, inspects template (when present) to write per-slide blocks within slot lengths; falls back to standard format defaults if templates absent',
    ],
  },
  {
    version: 'v2.2.9',
    date: 'April 30, 2026',
    changes: [
      'content-generator: removed pre-stored background lookup — every image is now generated fresh via Gemini (no more browsing backgrounds/ folder for matches)',
      'social-calendar: replaced "Ken Burns background video (pre-stored images)" references with "Gemini-generated images"',
      '.gitignore: added editor/IDE, env/secrets, Python, Node, and OS patterns',
    ],
  },
  {
    version: 'v2.2.8',
    date: 'April 28, 2026',
    changes: [
      'digital-marketing-analyst: date_preset changed from "last_30d" to "last_30dT" across all Windsor.ai calls (Google Ads, Meta, GA4) — fixes missing data for campaigns active on the current UTC day',
      'digital-marketing-analyst: removed outdated ~12-day Windsor data lag warnings — all three connectors are near-real-time',
      'digital-marketing-analyst: fixed invalid GA4 fields — removed "source" and "medium" from field lists, only "session_source_medium" is valid in Windsor',
      'digital-marketing-analyst: fiveagents_log_run metrics block rewritten — replaced literal zero placeholders with descriptive <actual_value> placeholders and added explicit warning to populate with real computed data (fixes agent_runs logging 0 data)',
      'data-analysis: same Windsor.ai fixes — date_preset → last_30dT, GA4 invalid field corrections, data lag note updated, per-connector field reference table added',
    ],
  },
  {
    version: 'v2.2.7',
    date: 'April 27, 2026',
    changes: [
      'brand-setup: added Step 10 — Initialize Workspace CLAUDE.md (auto-discovers agents/link.md path, writes Agent Identity + credential loader + brand context)',
      'brand-setup: Step 2 FiveAgents MCP row simplified — full setup instructions removed from overview, deferred to Step 7a',
      'brand-setup: LATE_API_KEY moved from Required to Required-for-social-publishing category in Step 2 and Step 7b',
      'brand-setup: Step 5 DataforSEO note corrected — keyword research skipped at Step 5, re-run research-strategy manually after Step 7',
      'brand-setup: Step 7b DataforSEO and Argil merged into single Optional table (was two separate Optional sections)',
      'brand-setup: Step 5 "Do not proceed" gate moved to after avatars.md (was incorrectly placed before it)',
      'brand-setup: Step 9 Slack message corrected N/16 → N/15 integrations',
      'brand-setup: Step 10 nested code block issues fixed (credential loader and Workspace Structure use indentation inside markdown template fence)',
    ],
  },
  {
    version: 'v2.2.6',
    date: 'April 27, 2026',
    changes: [
      'brand-setup: explicit "Save ALL keys to settings.local.json" instruction — FIVEAGENTS_API_KEY and all keys now explicitly listed for env save',
      'brand-setup: vault exclusion note clarified — keys not needing vault still MUST be saved to settings.local.json',
    ],
  },
  {
    version: 'v2.2.5',
    date: 'April 26, 2026',
    changes: [
      'all skills: added "Before Executing" section — every skill now reads agents/link.md before starting',
      'brand-setup: Step 1a — added "Act without asking" permission setting with risk disclaimer',
      'agents/link.md: updated skill table descriptions to match actual SKILL.md frontmatter',
      '.gitignore: added .DS_Store',
    ],
  },
  {
    version: 'v2.2.4',
    date: 'April 23, 2026',
    changes: [
      'brand-setup: Step 1b — added Domain Allowlist setting (Settings → Capabilities → Domain Allowlist → All Domains → ON)',
    ],
  },
  {
    version: 'v2.2.3',
    date: 'April 11, 2026',
    changes: [
      'brand-setup: enforced explicit confirmation gates at every step — "Do not proceed until..." added to Steps 1-9',
      'brand-setup: Step 1 reordered — 1a is now "Work in a Project" (project-first), 1b is settings configuration',
      'brand-setup: Step 1a rewrote project setup instructions (Projects area below chat input, clearer flow)',
      'brand-setup: Step 2 prerequisites — removed Playwright from MCP connectors table (not an OAuth connector)',
      'brand-setup: Step 6 logo — changed from paste-in-chat to file path input; uses file copy instead of save from chat',
      'brand-setup: Step 7c MCP table — removed Playwright row, renumbered remaining connectors',
      'brand-setup: Step 8 validation — removed Playwright test #10 (already confirmed in Step 4), renumbered tests 10-16',
      'brand-setup: Step 8 summary table — removed Playwright row',
      'brand-setup: Step 9 completion email JSON — removed Playwright integration entry',
      'brand-setup: Step 9 marked mandatory — always send completion email regardless of integrations configured',
      'brand-setup: Step 2 logo field updated — now shows file path example instead of "paste logo"',
      'agents/link.md: added brand-setup row to Skills table (was missing)',
      'agents/link.md: added Canva MCP to MCP Connectors section',
    ],
  },
  {
    version: 'v2.2.2',
    date: 'April 10, 2026',
    changes: [
      'creative-designer: gemini_generate_image result auto-saved to temp file — Python decodes to PNG on disk',
      'creative-designer: replaced image_add_text_overlay and image_add_logo gateway MCP tools with Python Pillow',
      'creative-designer: replaced late_upload_media MCP with Python requests.put to presigned S3 URL',
      'content-generator: same — gemini_generate_image result decoded via Python, Pillow for overlays, requests.put for upload',
      'background-generator: gemini_generate_image result decoded via Python to brands/{brand}/backgrounds/',
      'social-publisher: removed late_upload_media from tools list, added requests.put note',
      'brand-setup: updated logo step — references Python Pillow instead of image_add_logo gateway tool',
      'brand-setup: validation tests 5 & 6 now test Python Pillow instead of gateway MCP tools',
      'agents/link.md: updated tool list — removed image_add_text_overlay, image_add_logo, late_upload_media; added late_list_profiles, late_list_accounts',
      'fiveagents-gateway: removed image_add_text_overlay, image_add_logo tools (media.ts stubbed)',
      'fiveagents-gateway: removed late_upload_media tool from late.ts',
      'fiveagents-gateway: removed registerMediaTools from route.ts',
    ],
  },
  {
    version: 'v2.2.1',
    date: 'April 10, 2026',
    changes: [
      'brand-setup: Step 1b — added Cowork Project folder setup (user creates/selects project before brand files are created)',
      'brand-setup: Step 7b — full Zernio onboarding flow (account signup, profile creation, OAuth social platform connection)',
      'brand-setup: Step 7b — auto-discover Zernio profile ID and account IDs via late_list_profiles + late_list_accounts',
      'brand-setup: Step 7b — save per-platform account IDs as {BRAND}_LATE_FB/IG/LI env vars + Social Publishing section in brand.md',
      'brand-setup: Step 8 — removed redundant Playwright validation (already confirmed in Step 4)',
      'brand-setup: Step 8 — fixed email test param (html → html_body), DataforSEO location_code now dynamic from brand locale',
      'brand-setup: Step 8 — removed duplicate text report block (summary table is sufficient)',
      'brand-setup: Step 9 — completion email via brand-setup.ts server-side template (JSON payload, styled tables, status badges, action items)',
      'brand-setup: Step 1a — removed premature MCP connectors confirmation (moved to Step 7)',
      'fiveagents.io: new lib/email/templates/brand-setup.ts — styled email renderer for setup completion report',
      'fiveagents.io: registered brand-setup tag in email template index',
      'fiveagents-gateway: new late_list_profiles tool (GET /v1/profiles)',
      'fiveagents-gateway: new late_list_accounts tool (GET /v1/accounts with profileId filter)',
      'fiveagents-gateway: updated docs — 22 tools total',
    ],
  },
  {
    version: 'v2.2.0',
    date: 'April 10, 2026',
    changes: [
      'digital-marketing-analyst: agent now sends structured JSON instead of HTML — server-side template renders styled email',
      'digital-marketing-analyst: fixed double title bug (wrapInTemplate no longer renders subject as heading)',
      'digital-marketing-analyst: intermediate JSON schemas updated to match template (notes, top_recommendation, reach instead of lp_views)',
      'digital-marketing-analyst: removed all hardcoded currency (SGD), timezone (SGT), exchange rate (1.36) — reads from brands/{brand}/brand.md Locale',
      'brand-setup: added Locale section to brand.md template (Currency, Timezone, Meta USD exchange rate)',
      'brand-setup: Step 4 website analysis now infers locale from TLD, address, phone country code, currency symbols',
      'brand-setup: funnel.md cost benchmarks reference brand.md currency instead of hardcoded SGD',
      'social-publisher: replaced hardcoded Asia/Singapore timezone and SGT publish times with brand timezone from brand.md',
      'content-generator: replaced hardcoded 09:00 SGT and TZ=Asia/Singapore with brand timezone from brand.md',
      'social-calendar: replaced hardcoded 09:00 SGT with cron schedule reference',
      'research-strategy: replaced hardcoded USD→SGD 1.357 CPC conversion with brand.md exchange rate',
      'data-analysis: replaced hardcoded SGD/1.36 currency conversion with brand.md Locale',
      'commit-to-git: replaced hardcoded 11PM SGT and TZ=Asia/Singapore with brand timezone',
      'fiveagents.io email/send/route.ts: template routing — tag-based renderer dispatch (paid-ads-daily/weekly → paid-ads-brief.ts)',
      'fiveagents.io email/send/route.ts: wrapInTemplate simplified to logo + footer only (no duplicate title)',
      'fiveagents.io: new lib/email/templates/paid-ads-brief.ts — server-side HTML renderer ported from Link render_brief.py',
      'fiveagents.io: new lib/email/templates/index.ts — template registry for future skill renderers',
    ],
  },
  {
    version: 'v2.1.5',
    date: 'April 10, 2026',
    changes: [
      'content-generator: gemini_generate_image returns JSON — parse image_base64 before passing to image_add_text_overlay',
      'content-generator: image_add_text_overlay returns JSON — parse image_base64 before passing to image_add_logo',
      'content-generator: image_add_logo returns JSON — parse image_base64 for upload',
      'content-generator: model updated to gemini-3.1-flash-image-preview',
      'content-generator: clarified image_base64 source for pre-stored vs generated backgrounds in Step 4d',
      'creative-designer: gemini_generate_image returns JSON — parse image_base64 for pipeline',
      'creative-designer: image_add_text_overlay and image_add_logo return JSON — parse between steps',
      'creative-designer: model updated to gemini-3.1-flash-image-preview',
      'creative-designer: added aspect_ratio param to gemini_generate_image call',
      'creative-designer: fixed duplicate Step 5 heading — Argil section renumbered to Step 6',
      'creative-designer: fixed day-of-week rotation label (bottom/top → always bottom)',
      'creative-designer: added No Python PIL fallback note',
      'background-generator: gemini_generate_image returns JSON — parse image_base64 to save file',
      'background-generator: model updated to gemini-3.1-flash-image-preview',
      'background-generator: fixed "Nano Banana" reference → Gemini in prompt rules',
      'background-generator: added No Python PIL fallback note',
    ],
  },
];
