// Version information (production)
const DEFAULT_VERSION = 'v2.4.3';
const DEFAULT_DATE = 'May 07, 2026';

// Export constants initially with default values
export let APP_VERSION = DEFAULT_VERSION;
export let RELEASE_DATE = DEFAULT_DATE;

// NOTE: Keep only last 15 versions to prevent git overload (following Next.js pattern)
// Full history available in GitHub releases and git commits
export let VERSION_HISTORY: Array<{ version: string; date: string; changes: string[] }> = [
  {
    version: 'v2.4.3',
    date: 'May 07, 2026',
    changes: [
      'agents/link.md: one-time audit of every skill\'s Deps cell against actual tool calls in each SKILL.md — 19 of 22 skill rows corrected. Stale claims removed: data-analysis (PostHog), campaign-presenter (Gamma), outreach-sequencer (Apollo.io), investor-update-writer (Gamma), meeting-analyzer (Calendly). Missing tokens added: MCP: Slack on 6 skills (social-publisher, digital-marketing-analyst, social-calendar, proposal-generator, churn-predictor, outreach-sequencer), Gateway: Argil on creative-designer + content-generator, MCP: Notion on background-generator, MCP: Google Drive + Gmail on meeting-analyzer, MCP: PayPal (opt) + Notion + Google Drive (opt) on financial-reporter, Gateway: email on outreach-sequencer, MCP: Gmail on churn-predictor, MCP: Stripe (opt) + Gateway: email (opt) on invoice-collector. Missing Files refs added across most skills (audience.md, product.md, competitors.md, design-system/ opt). Companion fix: removed MCP: Notion from social-publisher row (initial cleanup that motivated the audit).',
      'brand-setup: Step 10 email payload — added top-level brand_name field. Display name (e.g. "Five Agents"), read from the first # heading in brands/{brand}/brand.md. Lets the server-side template render the brand\'s actual name in the email title instead of the slug.',
      'brand-setup: Step 8d-iv — clarified that connected_tools[] derivation reads agents/link.md Deps as the single source of truth (no per-agent table here).',
      'brand-setup: Step 8d-i translation table — added "PayPal MCP → PayPal (revenue)" row to match link.md\'s expanded Deps vocabulary (financial-reporter now lists PayPal opt).',
      'plugin-update: Step 5b email payload — added top-level brand_name field, mirrors the same field added to brand-setup Step 10 so the upgrade email title also renders the display name.',
    ],
  },
  {
    version: 'v2.4.2',
    date: 'May 07, 2026',
    changes: [
      'brand-setup: Step 8d agent_readiness[] schema — JSON example in 8d-iii and Step 10 email payload brought into sync; added `name` (renamed from `agent`), `category`, `status_label`, and `connected_tools[]` fields. Step 10 was lagging the 8d-iii schema after v2.4.1.',
      'brand-setup: Step 8d-ii / 8d-iii / Step 10 Slack DM — dropped "run on schedule starting today" framing in favor of "configured and available to run" / "configured and ready to run". Three call-sites were contradicting each other after v2.4.1.',
      'brand-setup: Step 8d-iv (NEW) — derivation rule for connected_tools[]: pull each agent\'s MCP:/Gateway: tokens from agents/link.md Deps column, translate via 8d-i, preserve (opt) markers. Replaces a duplicate per-agent mapping table that would have drifted from link.md. Keeps agents/link.md as the single source of truth (matching its own v2.4.1 claim).',
      'plugin-update: Step 4b — references brand-setup Step 8d-iv derivation rule for connected_tools[] (pulled from agents/link.md Deps + 8d-i translation) instead of a separate mapping table.',
      'plugin-update: Step 5b Slack DM "no fixes needed" line synchronized with brand-setup Step 10 — "configured and ready to run" instead of "ready to run on schedule".',
    ],
  },
  {
    version: 'v2.4.1',
    date: 'May 07, 2026',
    changes: [
      'agents/link.md: Skills table extended with Area (Marketing/Sales/Customer Success/Finance/Strategy/Productivity/Setup) and Deps columns — single source-of-truth for the agent readiness matrix that brand-setup Step 8d and plugin-update Step 4b compute. Added prefix notation guide (MCP: / Gateway: / Files: / Env: with (opt) marker) and per-skill dep mappings for all 22 entries.',
      'brand-setup: Step 2 prereqs table — added 6 business-ops MCP rows (Apollo.io, Calendly, Stripe, Xero, PostHog, Gamma) so users see what they\'ll be asked to connect upfront',
      'brand-setup: Step 3 directory tree + Step 9b Workspace Structure — added 5 v2.4.0 brand-context files (sales/CS/finance/investors/operations) with skip annotations for the conditional ones',
      'brand-setup: Step 7c — added "Business-operations MCPs" walkthrough block with explicit per-MCP prompts (each names dependent skill + skip impact). Closes the gap where Step 8c-bis would probe MCPs the user was never asked to connect.',
      'brand-setup: Steps 5g/5h/5i/5j/5k — added "Read existing context first" mapping table at the top of each new sub-step. Lists which existing brand files (brand.md, audience.md, product.md, etc.) to pre-fill from, so the agent never asks for info already on disk.',
      'brand-setup: Step 8d (NEW) — Agent Readiness Summary. Translation table (technical → business labels), status rules (Ready / Works with limitations / Not ready / You skipped), display format with worked example, structured save schema for Step 10. Owners get the business answer ("which agents will run on my brand starting today"), not the engineering answer ("which connections passed").',
      'brand-setup: Step 10 email payload — restructured around agent_readiness[] + readiness_summary as primary blocks; demoted connections[] and files[] to diagnostic detail. Slack DM leads with readiness counts + top 3 fixes instead of integration count. Requires server-side template update at fiveagents/src/lib/email/templates/brand-setup.ts (handed off via JSON instruction spec).',
      'plugin-update: Step 1e — added MCP probe rows for PostHog, Gamma, Meta Ads MCP (optional). Now matches every connector validated by brand-setup Step 8c-bis.',
      'plugin-update: Step 2 gap report example — expanded to surface business-ops MCPs and the 5 v2.4.0 brand-context files',
      'plugin-update: Step 3a — added top-of-section pre-fill rule + per-bullet pre-fill summaries for the 5 v2.4.0 files. In plugin-update context the v2.0 source files are essentially guaranteed to exist, so pre-fill is mandatory; agent reads existing brand files and drafts answers instead of asking from scratch.',
      'plugin-update: Step 3f — rewrote MCP gap-fill flow with explicit per-MCP walkthrough prompts for all 14 MCPs (was only Windsor + Playwright). Closes the gap where business-ops MCPs flagged in Step 1e were silently skipped during interactive fill.',
      'plugin-update: Step 3g — fixed CLAUDE.md re-embed bug. Previous version only refreshed the version stamp comment, leaving the embedded agents/link.md body unchanged after a git pull. New logic strips link.md frontmatter, builds a full BEGIN/END block (stamp + body), and atomically replaces everything between the markers using re.sub with re.DOTALL + lambda replacement (avoids backslash interpretation). Added post-write verification: grep CLAUDE.md for a string unique to the new version.',
      'plugin-update: Step 4b (NEW) + Step 5b — Agent Readiness Summary using brand-setup Step 8d spec; same readiness-first email + Slack format. Inputs come from Step 1 audit overlaid with Step 3 fix outcomes, so the matrix reflects post-fix state.',
    ],
  },
  {
    version: 'v2.4.0',
    date: 'May 07, 2026',
    changes: [
      '10 new business-operations skills shipped: apollo-lead-prospector, outreach-sequencer, proposal-generator (sales pipeline); customer-onboarder, churn-predictor (retention); invoice-collector, financial-reporter (back-office); competitor-monitor, investor-update-writer (strategy); meeting-analyzer (productivity)',
      'agents/link.md: rewritten from "marketing agent" → "business operations agent"; added 5 new context-file rows (sales.md, customer-success.md, finance.md, investors.md, operations.md); added 4 new skill chains (Sales pipeline, Customer retention, Monthly close, Strategic intelligence); added Apollo.io / Calendly / Stripe / Xero / Gamma MCP rows',
      'brand-setup: Step 5 expanded with 6 new sub-steps (5g sales, 5h customer-success, 5i finance, 5j investors, 5k operations, 5l competitors.md extension verification); Step 7 documents 7 new auto-bootstrapped Notion DB env vars; Step 8 adds probes for Apollo/Calendly/Stripe/Xero; Step 10 files[] block expanded',
      'brand-setup: full UX intro audit — added top-level "What this skill does" overview with 10-step time-budget table, plus per-step intro paragraphs across all 10 main steps and the 6 new sub-steps',
      'plugin-update: Step 1a/1d/1e/1j extended to detect new context files, env vars, MCPs, and skill versions; Step 3a/3e/3j extended with fill handlers and changelog → brand-action mappings for all 10 new skills; conditional consent gates added for investors.md and operations.md',
      'plugin-update: matching UX intro audit — top-level overview + per-step intros for all 6 steps with time estimates',
      'commit-to-git workflow: Step 4a hardened with env-var-first DB resolution (`AGENTS_LIBRARY_DB`) + fuzzy name search fallback + auto-persist of resolved ID — survives Notion DB renames and workspace moves',
      'commit-to-git skill + workflow: moved out of plugins/link-skills/ into the new gitignored /admin-skills/ + /workflow/ folders at repo root — release tooling separated from the marketplace plugin',
      'creative-designer: fixed is_vertical edge case where IG portrait 4:5 (1080×1350) was incorrectly receiving 9:16 safe zones; replaced with `is_story_reel = (target_h / target_w) >= 1.7`',
      'social-calendar + content-generator + background-generator: normalized Notion MCP tool prefix from legacy `mcp__notion__notion-*` to canonical `mcp__claude_ai_Notion__notion-*`; replaced obsolete `API-update-a-block` / `API-query-data-source` calls with current connector tools',
      'docs/metrics-spec.md: sanitized real campaign data, real spend numbers, and real competitive positioning from example payloads (Acme-style placeholders); plugin.json: replaced real Slack user ID example with generic format',
    ],
  },
  {
    version: 'v2.3.7',
    date: 'May 07, 2026',
    changes: [
      'content-generator: Step 4a safe zone table — added note clarifying Top 14% column applies to logo placement only, not text (add_text_overlay has no top constraint)',
      'content-generator + creative-designer: add_logo positions dict — added # NEVER USE comments on bottom-right and bottom-left entries; text always occupies the bottom zone so these positions are forbidden',
      'creative-designer: frontmatter description — removed stale "with Nano Banana Pro" (Nano Banana replaced by Gemini in v2.2.2)',
      'creative-designer: add_text_overlay prose note — clarified 18% safe-zone offset applies to 9:16 only; feed canvases use flat 60 px buffer instead',
      'creative-designer/style-guide.md — replaced "Nano Banana" brand name with "Claude\'s continue_editing" in two Don\'t rules (more durable phrasing)',
      'link.md: skills table — removed stale "with Nano Banana Pro" from creative-designer description row',
      'commit-to-git workflow — Step 3b: added "already bumped this session" rule (do not re-increment if maintenance sections were updated in the current session); Step 5a: added branch to use highest existing version instead of incrementing again',
    ],
  },
  {
    version: 'v2.3.2',
    date: 'May 06, 2026',
    changes: [
      'brand-setup: Arguments section added — /brand-setup -- project created skips Step 1a and starts at 1b, ensuring all setup steps run inside the project session',
      'brand-setup: Step 1a — after project creation, user is redirected into the project session to continue; session does not proceed in-place',
      'brand-setup: carousel + story design prompts (Step A) — added IMAGE SLOTS AND SIZE LIMIT paragraph banning embedded images/base64/bundled photos, mandating uploads/<slot>.png placeholder naming, enforcing 3 MB export limit',
      'brand-setup: Step 4c-i Step C — 3 MB size check added before shutil.copytree; if exceeded, blocks copy and surfaces claude.ai/design re-export prompt',
      'brand-setup: Step 4c-ii Step C — same 3 MB size check before copy with story-specific re-export prompt',
      'plugin-update: Step 3c upload sub-flow — step 0 size check (3 MB) added before zip/upload; blocks upload and surfaces re-export prompt if limit exceeded; Case 3 reference updated to Steps 0–5',
    ],
  },
  {
    version: 'v2.3.1',
    date: 'May 06, 2026',
    changes: [
      'brand-setup: compute_version_hash fixed — added __MACOSX to exclusion set, unified IGNORE/IGNORE_DIRS into single set, switched path-part check to rel.split("/"); without this fix macOS-extracted templates produce a different hash than the gateway, causing drift detection to permanently report mismatch',
      'brand-setup: carousel + story zip creation loops use same unified IGNORE set as compute_version_hash (was using separate IGNORE_DIRS variable)',
      'brand-setup: carousel template prompt (Step 4c-i Step A) — replaced stale Playwright offscreen DOM ID requirements with .slide CSS class convention and uploads/ slot-naming rule',
      'brand-setup: story template prompt (Step 4c-ii Step A) — same Playwright DOM ID removal; .slide CSS class and server-side rendering convention added',
      'brand-setup: template_list Step F calls — brand parameter documented as OPTIONAL in both carousel and story verification gates',
      'plugin-update: compute_version_hash in Step 1h — same __MACOSX fix as brand-setup; template_list brand parameter documented as OPTIONAL',
      'content-generator: template_list verbose response now documents entry_html field; brand parameter marked OPTIONAL; template_render updated with optional version_hash field and PNG/JPEG slots type',
      'creative-designer: template_list entry_html added to bullet 2 and quality checklist; template_render bullet 6 updated with version_hash optional and PNG/JPEG slots',
    ],
  },
  {
    version: 'v2.3.0',
    date: 'May 06, 2026',
    changes: [
      'link.md: External APIs section — added template_upload / template_list / template_render gateway tools for server-side carousel/story rendering',
      'brand-setup: Step 9a — version stamp extracted from link.md Maintenance table; embedded into CLAUDE.md as <!-- link.md version: ... | Last Changed: ... | Embedded: ... --> comment inside BEGIN/END markers on every brand-setup and plugin-update run',
      'brand-setup: Steps 4c-i/ii — template upload sub-flow added: zip templates (excluding __MACOSX, .DS_Store, node_modules), call template_upload gateway, persist ## Social Templates section to brand.md with template IDs, verify via template_list',
      'brand-setup: Step 9c Visual System block updated — gateway template_render path documented; no local Playwright required for rendering',
      'content-generator: Step 4c-template — migrated from local Playwright render to gateway template_render MCP tool; shell_path resolved via template_list as template_id; no local browser required',
      'creative-designer: Step 4a template-path — gateway renders templates server-side via template_render MCP; Playwright removed; stale intro text corrected',
      'plugin-update: new skill — comprehensive brand audit with version gap detection (Step 0: reads version.ts + brand.md Plugin Version + all 14 maintenance sections to build delta table); Step 1j skill/agent version audit; Step 3g unconditional version stamp refresh; Step 3j changelog-driven brand action mapping; Step 5 writes plugin version to brand.md after completion',
      'all 14 files: ## Maintenance sections added to every SKILL.md and link.md — Version, Last Changed, Description, last 5 changelog entries per file',
      'commit-to-git workflow: overhauled — Step 3 audits maintenance section freshness, Step 4 syncs all 14 rows to Notion "Five Agents - Agents Library" DB, Step 6 scoped to plugins/link-skills/ only, Step 7 push + tag + ls-remote confirmation',
    ],
  },
  {
    version: 'v2.2.15',
    date: 'May 05, 2026',
    changes: [
      'brand-setup: Step 9 ↔ Step 10 swap — CLAUDE.md initialization (was Step 10) is now Step 9 and runs BEFORE the Step 10 completion email, so the email reflects the actual CLAUDE.md write status and visual-asset detection rather than lying about success when the post-validation steps fail',
      'brand-setup: Step 4b (Claude Design System) MANDATORY → OPTIONAL — when absent, downstream skills fall back to brand.md colors/voice + Google Font names from Step 4; no hard block on missing design-system',
      'brand-setup: agents/link.md visual rule softened to match — design-system/ is now "optional but recommended"; new lookup order documented: design-system/ (when present) → brand.md (universal fallback)',
      'brand-setup: Step 4b/4c install flow rewritten — user provides path to unzipped folder, agent copies + renames into canonical brands/{brand}/{folder}/ (mirrors Step 6 logo pattern); Cowork-aware path guidance ("must be inside your project mount"); idempotent re-run support via shutil.rmtree before copytree; nested-zip detection',
      'brand-setup: Step 6 (logo) install now path-based with Python copy + validation — matches the Step 4b/4c pattern',
      'brand-setup: Step 9a glob patterns Cowork-aware — $CLAUDE_CONFIG_DIR/**/agents/link.md tried first (canonical inside Cowork sandbox), with $HOME/.claude/ + Windows/macOS host fallbacks; eliminates the "couldn\'t auto-detect, please paste path" prompt in 99% of Cowork runs',
      'brand-setup: Step 9b "Workspace Defaults" multi-brand handling — append "### Brand: {brand}" sub-block on re-run instead of overwriting prior brands\' defaults; DEFAULT_BRAND env var still selects which brand is active per session',
      'brand-setup: Step 9c — best-effort, non-mandatory detection of design-system/, social-carousel-template/, social-story-template/; results wired into CLAUDE.md as "Visual System" section bracketed by BEGIN/END markers for idempotent re-runs; step is independently re-runnable',
      'brand-setup: Step 10 (completion email) files[] vocab harmonized to `present | missing | failed` across all rows (was a mix of `created`/`installed`/`updated`/`missing` per-row); Slack message includes CLAUDE.md write status; action_items rule explicitly carves out Meta Ads MCP skips and other intentionally-optional integrations',
      'brand-setup: Step 4c rewrite — social templates are now React + Babel apps with EDITMODE-BEGIN/END JSON contracts (not blank background shells); both Carousel (6 slides: Cover + 4 signs + CTA) and Story (6 slides: Hook → Problem → Solution → Proof → Offer → CTA, three direction styles A/B/C) prompts produce a fully-laid-out template app with stable export DOM IDs; agent verifies the EDITMODE block parses and contains all required keys at install time',
      'content-generator: shell-path replaced with template-path (Step 4c-template) — read entry HTML, parse EDITMODE JSON, merge post copy, write modified HTML to tmp, render in Playwright, screenshot each slide via stable offscreen export DOM IDs (#export-cover/#export-s2.../#export-cta for carousel; #export-{A|B|C}-0...-5 for story)',
      'content-generator: Notion calendar schema gained Direction column at index 9, pushing Status to index 10 (now 11 columns: Date/Platform/Format/Topic/Persona/ContentAngle/CTA/Hashtags/ImageBrief/Direction/Status); Step 6 status update + cell index references updated',
      'content-generator: new Step 3b — generate structured _copy.json for template-path posts matching the template\'s key contract (cover_*/s2-5_*/cta_* for carousel, s1-6_* for story); skipped for non-template posts',
      'content-generator: Gemini + Pillow text + Pillow logo fallback path (Step 4c-image / 4d / 4e) preserved verbatim, including v2.2.14\'s text overlay improvements and Step 4h visual verification — universal fallback for LinkedIn, non-template formats, and any template-path failure',
      'content-generator: design-system/ MANDATORY → OPTIONAL — never log a `failed` run for missing visual assets; brand.md provides the fallback colors/voice',
      'social-calendar: Direction column added to the planning table — picker rules per format (Carousel: coverVariant-bodyVariant combos like type-allnumbers/sticker-editorial/editorial-mixed; Story/Reel: A/B/C per template subtitle hint; LinkedIn / Reel(Argil): blank); Notion table column count 10 → 11; Quality Checklist requires Direction populated',
      'creative-designer: Step 4a switched from shell-path to template-path; delegates canonical implementation to content-generator/SKILL.md; Step 4b Gemini + Pillow fallback unchanged (incl. v2.2.14\'s Step 3b visual verification); design-system/ mandate softened to optional with brand.md fallback',
      'content-creation: Carousel/Story copy outputs now produce structured _copy.json next to _copy.md, matching the templates\' EDITMODE key contracts with per-key character budgets; Direction is explicitly NOT content-creation\'s concern (lives in social-calendar\'s Notion column); naming convention split into social ([Slug]_[Date]) vs non-social ([ContentType]_[Date])',
      'background-generator: Role section updated to clarify it produces a separate general-purpose backgrounds library at brands/{brand}/backgrounds/ (used by Reel video production), distinct from the social-{carousel,story}-template/ template apps that Steps 4c-i / 4c-ii install',
    ],
  },
  {
    version: 'v2.2.14',
    date: 'May 05, 2026',
    changes: [
      'content-generator + creative-designer: text overlay — text_align fixed to always "center"; day-of-week rotation now alternates text_position between "bottom" (Mon/Wed/Fri) and "top" (Tue/Thu/Sat) instead of rotating left/center/right alignment',
      'content-generator + creative-designer: add_text_overlay stub replaced with complete Pillow implementation — uses textwrap.wrap() with max_chars calculated from canvas width and font size, draws each line centered via textbbox pixel measurement; text cannot overflow canvas',
      'content-generator + creative-designer: gradient scrim dynamically sized to fit the text block (no fixed 45% assumption); scrim direction flips correctly for top vs bottom position',
      'content-generator: Step 4h (mandatory visual verification before Zernio) — agent reads final image and checks text visibility, logo visibility, equal visual margins, contrast, and no overlap; fix table covers clipping, offset, blending, size, and overlap issues',
      'creative-designer: Step 3b (mandatory visual verification before Zernio upload) — same checks and fix table as content-generator; covers all per-client logo variations without assuming logo internal structure',
      'content-generator + creative-designer: fix table includes logo getbbox() crop for transparent-padding logos, scale adjustments, corner switching for busy backgrounds, semi-transparent backing for low-contrast logos',
    ],
  },
  {
    version: 'v2.2.13',
    date: 'May 05, 2026',
    changes: [
      'brand-setup: Meta Ads framing reversed — Windsor.ai with Meta Ads (Facebook Ads) connected is now the MANDATORY universal path for every brand (because Meta Ads MCP rollout cannot be guaranteed); the Meta Ads MCP at https://mcp.facebook.com/ads is an optional enhancement that flips downstream behavior only when explicitly opted into',
      'brand-setup: Step 2 prereq table — Windsor.ai marked *(required)* and now lists Google Ads + GA4 + Meta Ads as a combined required scope; Meta Ads MCP marked *(optional enhancement — limited rollout)* with explicit "skip without prejudice" wording',
      'brand-setup: Step 7c — Meta Ads section rewritten so Windsor.ai is the standard path and the MCP is the optional layer-on-top; user prompt for the MCP starts with "(Optional)" and reassures the user that skipping costs nothing because Windsor already covers Meta fully',
      'brand-setup: Step 7c Windsor.ai walkthrough — step 2 unconditionally instructs the user to connect Google Ads, GA4, AND Meta Ads in Windsor (no env-var conditional); Meta in Windsor is required regardless of MCP status',
      'brand-setup: Step 7c — META_ADS_SOURCE env var contract: only set to "meta_ads_mcp" when user successfully added the optional MCP; left unset otherwise (skills default to Windsor)',
      'brand-setup: Step 8 #14 — Windsor.ai test now verifies all three required connectors (Google Ads, GA4, Facebook); fails ❌ if any is missing (no partial pass). #15 Meta Ads MCP — only runs when META_ADS_SOURCE=meta_ads_mcp; skipped (not failed) otherwise since Windsor already covers Meta',
      'brand-setup: Step 8 summary table + Step 9 JSON payload — Windsor.ai row is ✅/❌ only (no skip option), Meta Ads MCP row remains ✅/❌/⏭ with notes clarifying it is purely additive',
      'digital-marketing-analyst: Phase 2 Step 1 + Weekly Step 1b — Windsor.ai with source: "facebook" is the documented default path; Meta Ads MCP is the opt-in alternative with automatic fallback to Windsor on runtime error',
      'digital-marketing-analyst: Windsor field set verified live against Windsor get_fields(connector: "facebook") which exposes 741 fields. Field map covers campaign + adset_name/adset_id/adset_effective_status + ad_name/ad_id + clicks/impressions/ctr/spend/reach/frequency/cpm/cpc + actions_landing_page_view + actions_video_view + brand-funnel-specific actions_* conversion field — near-parity with Marketing API',
      'digital-marketing-analyst: removed false claims that Windsor Facebook is "campaign-level only" and "no conversion data available" (those claims dated to a pre-2026 Windsor API and were inaccurate)',
      'digital-marketing-analyst: meta_ads JSON block — added required "source" field ("windsor" | "meta_ads_mcp") so the dashboard can interpret which field-name space the data came from. On MCP→Windsor runtime fallback, source records the data actually used (windsor), not the path attempted first',
      'data-analysis: Step 1a — same default-Windsor / opt-in-MCP branching with explicit Windsor field map and conversion-event guidance from brands/{brand}/funnel.md; corrected Windsor capability claims',
      'agents/link.md: MCP Connectors list — Windsor.ai marked required (Google Ads + GA4 + Meta Ads); Meta Ads MCP marked optional enhancement with the META_ADS_SOURCE contract documented',
    ],
  },
  {
    version: 'v2.2.12',
    date: 'May 04, 2026',
    changes: [
      'brand-setup: Step 7b — explicit instruction to save DEFAULT_BRAND (active brand slug) and {BRAND}_NOTION_DB (Notion Social Calendar DB page ID) to .claude/settings.local.json env block; how-to-get-Notion-DB-ID note included',
      'brand-setup: Step 8d — new mandatory validation block (#18, #19) that checks DEFAULT_BRAND and {BRAND}_NOTION_DB are present in settings.local.json; both are non-skippable (❌ stops the flow)',
      'brand-setup: Step 8 summary table and Step 9 completion-email connections[] now include the two env-var checks; Step 9 Slack message integration count bumped 16 → 18',
      'brand-setup: Step 10b CLAUDE.md template — replaced "Active Brand" section with "Workspace Defaults" that hardcodes the brand slug and Notion DB ID inline (so any session sees them immediately) with an env-var fallback rule for stale/copied workspaces; placeholder list extended to {brand} / {BRAND} / {notion_db_id}',
      'brand-setup: normalized {BRAND} env-var prefix convention (uppercased, hyphens removed) across Step 7b note, Step 8d, Step 8 summary, Step 9 connections, Step 10b template — replaces accidental {BRAND_UPPER} variants',
    ],
  },
  {
    version: 'v2.2.11',
    date: 'May 04, 2026',
    changes: [
      'brand-setup: Step 10 — CLAUDE.md now embeds the full content of agents/link.md directly (frontmatter stripped) instead of writing an absolute-path reference; workspace becomes self-contained for scheduled runs and fresh clones',
      'brand-setup: Step 10b uses BEGIN/END markers (<!-- BEGIN agents/link.md (embedded by brand-setup) -->) for idempotent re-runs; backwards-compat handling replaces older absolute-path Agent Identity blocks',
      'brand-setup: Meta Ads — added official Meta Ads MCP custom connector (https://mcp.facebook.com/ads); replaces Windsor.ai for Meta Ads (Facebook + Instagram) campaign data across Step 2 prereqs, Step 7c connector flow, Step 8 validation, Step 8 summary table, Step 9 completion email JSON',
      'brand-setup: Windsor.ai narrowed to Google Ads + GA4 only; vault-storage note in Step 7b clarifies Meta Ads credentials live with the Meta Ads MCP, not Windsor; integration count bumped 15 → 16 in Step 9 Slack message',
      'digital-marketing-analyst: Phase 2 daily Meta pull and Weekly Step 1b migrated from Windsor.ai (source: "facebook") to the Meta Ads MCP; ad_set / ad / lp_views / video_views / conversions / cpm now expected (Meta Marketing API surfaces them); Notes data-sources / data-lag / TikTok-future updated; lp_views note no longer says "not in Windsor"',
      'data-analysis: Step 1a split — Windsor.ai block for Google Ads + GA4, separate Meta Ads MCP block for Facebook + Instagram; inputs table data-source row updated; fallback prompt mentions both connectors',
      'agents/link.md: MCP Connectors list — Windsor.ai narrowed to Google Ads + GA4; new Meta Ads MCP custom-connector entry',
    ],
  },
  {
    version: 'v2.2.10',
    date: 'May 04, 2026',
    changes: [
      'brand-setup: Step 4b (mandatory) — Claude Design system installed at brands/{brand}/design-system/ via claude.ai/design Share → Download Project as .zip',
      'brand-setup: Step 4c (optional) — Social Carousel (4:5) and Social Story (9:16) Claude Design templates installed at brands/{brand}/social-carousel-template/ and social-story-template/',
      'brand-setup: prerequisites overview, directory structure, and Step 9 completion email updated to include design-system + template folders',
      'brand-setup: Step 10a hardened to enforce ABSOLUTE path for agents/link.md — os.path.abspath(os.path.realpath(...)) + os.path.isabs assertion, manual-fallback path is also normalized and validated',
      'brand-setup: Step 10b explicit instruction that link.md path written into CLAUDE.md must be absolute (verbatim with drive letter on Windows / leading slash on Unix)',
      'agents/link.md: design-system/ added to Context Files as authoritative for visuals; carousel/story templates listed as optional with fallback; new Visual consistency rule',
      'creative-designer: design-system/ is source of truth (replaces brand.md as primary visual reference); new Step 4a branches Carousel/Story to template-render via Playwright when template folder exists; Gemini still required to fill visual slots inside template',
      'content-generator: Step 2 reads design-system/ (mandatory) + detects optional templates; Step 4c-template renders via Playwright for IG/FB Carousel/Story when templates installed; falls back to Gemini+Pillow if templates absent or Playwright fails; quality checklist guards against double-stamp text/logo on template path',
      'content-creation: reads design-system/ to size copy against text frames; for IG/FB carousel/story copy, inspects template (when present) to write per-slide blocks within slot lengths; falls back to standard format defaults if templates absent',
    ],
  },
  {
    version: 'v2.2.9',
    date: 'April 30, 2026',
    changes: [
      'content-generator: removed pre-stored background lookup — every image is now generated fresh via Gemini (no more browsing backgrounds/ folder for matches)',
      'social-calendar: replaced "Ken Burns background video (pre-stored images)" references with "Gemini-generated images"',
      '.gitignore: added editor/IDE, env/secrets, Python, Node, and OS patterns',
    ],
  },
];
