// Version information (production)
const DEFAULT_VERSION = 'v2.2.10';
const DEFAULT_DATE = 'May 04, 2026';

// Export constants initially with default values
export let APP_VERSION = DEFAULT_VERSION;
export let RELEASE_DATE = DEFAULT_DATE;

// NOTE: Keep only last 15 versions to prevent git overload (following Next.js pattern)
// Full history available in GitHub releases and git commits
export let VERSION_HISTORY: Array<{ version: string; date: string; changes: string[] }> = [
  {
    version: 'v2.2.10',
    date: 'May 04, 2026',
    changes: [
      'brand-setup: Step 4b (mandatory) — Claude Design system installed at brands/{brand}/design-system/ via claude.ai/design Share → Download Project as .zip',
      'brand-setup: Step 4c (optional) — Social Carousel (4:5) and Social Story (9:16) Claude Design templates installed at brands/{brand}/social-carousel-template/ and social-story-template/',
      'brand-setup: prerequisites overview, directory structure, and Step 9 completion email updated to include design-system + template folders',
      'brand-setup: Step 10a hardened to enforce ABSOLUTE path for agents/link.md — os.path.abspath(os.path.realpath(...)) + os.path.isabs assertion, manual-fallback path is also normalized and validated',
      'brand-setup: Step 10b explicit instruction that link.md path written into CLAUDE.md must be absolute (verbatim with drive letter on Windows / leading slash on Unix)',
      'agents/link.md: design-system/ added to Context Files as authoritative for visuals; carousel/story templates listed as optional with fallback; new Visual consistency rule',
      'creative-designer: design-system/ is source of truth (replaces brand.md as primary visual reference); new Step 4a branches Carousel/Story to template-render via Playwright when template folder exists; Gemini still required to fill visual slots inside template',
      'content-generator: Step 2 reads design-system/ (mandatory) + detects optional templates; Step 4c-template renders via Playwright for IG/FB Carousel/Story when templates installed; falls back to Gemini+Pillow if templates absent or Playwright fails; quality checklist guards against double-stamp text/logo on template path',
      'content-creation: reads design-system/ to size copy against text frames; for IG/FB carousel/story copy, inspects template (when present) to write per-slide blocks within slot lengths; falls back to standard format defaults if templates absent',
    ],
  },
  {
    version: 'v2.2.9',
    date: 'April 30, 2026',
    changes: [
      'content-generator: removed pre-stored background lookup — every image is now generated fresh via Gemini (no more browsing backgrounds/ folder for matches)',
      'social-calendar: replaced "Ken Burns background video (pre-stored images)" references with "Gemini-generated images"',
      '.gitignore: added editor/IDE, env/secrets, Python, Node, and OS patterns',
    ],
  },
  {
    version: 'v2.2.8',
    date: 'April 28, 2026',
    changes: [
      'digital-marketing-analyst: date_preset changed from "last_30d" to "last_30dT" across all Windsor.ai calls (Google Ads, Meta, GA4) — fixes missing data for campaigns active on the current UTC day',
      'digital-marketing-analyst: removed outdated ~12-day Windsor data lag warnings — all three connectors are near-real-time',
      'digital-marketing-analyst: fixed invalid GA4 fields — removed "source" and "medium" from field lists, only "session_source_medium" is valid in Windsor',
      'digital-marketing-analyst: fiveagents_log_run metrics block rewritten — replaced literal zero placeholders with descriptive <actual_value> placeholders and added explicit warning to populate with real computed data (fixes agent_runs logging 0 data)',
      'data-analysis: same Windsor.ai fixes — date_preset → last_30dT, GA4 invalid field corrections, data lag note updated, per-connector field reference table added',
    ],
  },
  {
    version: 'v2.2.7',
    date: 'April 27, 2026',
    changes: [
      'brand-setup: added Step 10 — Initialize Workspace CLAUDE.md (auto-discovers agents/link.md path, writes Agent Identity + credential loader + brand context)',
      'brand-setup: Step 2 FiveAgents MCP row simplified — full setup instructions removed from overview, deferred to Step 7a',
      'brand-setup: LATE_API_KEY moved from Required to Required-for-social-publishing category in Step 2 and Step 7b',
      'brand-setup: Step 5 DataforSEO note corrected — keyword research skipped at Step 5, re-run research-strategy manually after Step 7',
      'brand-setup: Step 7b DataforSEO and Argil merged into single Optional table (was two separate Optional sections)',
      'brand-setup: Step 5 "Do not proceed" gate moved to after avatars.md (was incorrectly placed before it)',
      'brand-setup: Step 9 Slack message corrected N/16 → N/15 integrations',
      'brand-setup: Step 10 nested code block issues fixed (credential loader and Workspace Structure use indentation inside markdown template fence)',
    ],
  },
  {
    version: 'v2.2.6',
    date: 'April 27, 2026',
    changes: [
      'brand-setup: explicit "Save ALL keys to settings.local.json" instruction — FIVEAGENTS_API_KEY and all keys now explicitly listed for env save',
      'brand-setup: vault exclusion note clarified — keys not needing vault still MUST be saved to settings.local.json',
    ],
  },
  {
    version: 'v2.2.5',
    date: 'April 26, 2026',
    changes: [
      'all skills: added "Before Executing" section — every skill now reads agents/link.md before starting',
      'brand-setup: Step 1a — added "Act without asking" permission setting with risk disclaimer',
      'agents/link.md: updated skill table descriptions to match actual SKILL.md frontmatter',
      '.gitignore: added .DS_Store',
    ],
  },
  {
    version: 'v2.2.4',
    date: 'April 23, 2026',
    changes: [
      'brand-setup: Step 1b — added Domain Allowlist setting (Settings → Capabilities → Domain Allowlist → All Domains → ON)',
    ],
  },
  {
    version: 'v2.2.3',
    date: 'April 11, 2026',
    changes: [
      'brand-setup: enforced explicit confirmation gates at every step — "Do not proceed until..." added to Steps 1-9',
      'brand-setup: Step 1 reordered — 1a is now "Work in a Project" (project-first), 1b is settings configuration',
      'brand-setup: Step 1a rewrote project setup instructions (Projects area below chat input, clearer flow)',
      'brand-setup: Step 2 prerequisites — removed Playwright from MCP connectors table (not an OAuth connector)',
      'brand-setup: Step 6 logo — changed from paste-in-chat to file path input; uses file copy instead of save from chat',
      'brand-setup: Step 7c MCP table — removed Playwright row, renumbered remaining connectors',
      'brand-setup: Step 8 validation — removed Playwright test #10 (already confirmed in Step 4), renumbered tests 10-16',
      'brand-setup: Step 8 summary table — removed Playwright row',
      'brand-setup: Step 9 completion email JSON — removed Playwright integration entry',
      'brand-setup: Step 9 marked mandatory — always send completion email regardless of integrations configured',
      'brand-setup: Step 2 logo field updated — now shows file path example instead of "paste logo"',
      'agents/link.md: added brand-setup row to Skills table (was missing)',
      'agents/link.md: added Canva MCP to MCP Connectors section',
    ],
  },
  {
    version: 'v2.2.2',
    date: 'April 10, 2026',
    changes: [
      'creative-designer: gemini_generate_image result auto-saved to temp file — Python decodes to PNG on disk',
      'creative-designer: replaced image_add_text_overlay and image_add_logo gateway MCP tools with Python Pillow',
      'creative-designer: replaced late_upload_media MCP with Python requests.put to presigned S3 URL',
      'content-generator: same — gemini_generate_image result decoded via Python, Pillow for overlays, requests.put for upload',
      'background-generator: gemini_generate_image result decoded via Python to brands/{brand}/backgrounds/',
      'social-publisher: removed late_upload_media from tools list, added requests.put note',
      'brand-setup: updated logo step — references Python Pillow instead of image_add_logo gateway tool',
      'brand-setup: validation tests 5 & 6 now test Python Pillow instead of gateway MCP tools',
      'agents/link.md: updated tool list — removed image_add_text_overlay, image_add_logo, late_upload_media; added late_list_profiles, late_list_accounts',
      'fiveagents-gateway: removed image_add_text_overlay, image_add_logo tools (media.ts stubbed)',
      'fiveagents-gateway: removed late_upload_media tool from late.ts',
      'fiveagents-gateway: removed registerMediaTools from route.ts',
    ],
  },
  {
    version: 'v2.2.1',
    date: 'April 10, 2026',
    changes: [
      'brand-setup: Step 1b — added Cowork Project folder setup (user creates/selects project before brand files are created)',
      'brand-setup: Step 7b — full Zernio onboarding flow (account signup, profile creation, OAuth social platform connection)',
      'brand-setup: Step 7b — auto-discover Zernio profile ID and account IDs via late_list_profiles + late_list_accounts',
      'brand-setup: Step 7b — save per-platform account IDs as {BRAND}_LATE_FB/IG/LI env vars + Social Publishing section in brand.md',
      'brand-setup: Step 8 — removed redundant Playwright validation (already confirmed in Step 4)',
      'brand-setup: Step 8 — fixed email test param (html → html_body), DataforSEO location_code now dynamic from brand locale',
      'brand-setup: Step 8 — removed duplicate text report block (summary table is sufficient)',
      'brand-setup: Step 9 — completion email via brand-setup.ts server-side template (JSON payload, styled tables, status badges, action items)',
      'brand-setup: Step 1a — removed premature MCP connectors confirmation (moved to Step 7)',
      'fiveagents.io: new lib/email/templates/brand-setup.ts — styled email renderer for setup completion report',
      'fiveagents.io: registered brand-setup tag in email template index',
      'fiveagents-gateway: new late_list_profiles tool (GET /v1/profiles)',
      'fiveagents-gateway: new late_list_accounts tool (GET /v1/accounts with profileId filter)',
      'fiveagents-gateway: updated docs — 22 tools total',
    ],
  },
  {
    version: 'v2.2.0',
    date: 'April 10, 2026',
    changes: [
      'digital-marketing-analyst: agent now sends structured JSON instead of HTML — server-side template renders styled email',
      'digital-marketing-analyst: fixed double title bug (wrapInTemplate no longer renders subject as heading)',
      'digital-marketing-analyst: intermediate JSON schemas updated to match template (notes, top_recommendation, reach instead of lp_views)',
      'digital-marketing-analyst: removed all hardcoded currency (SGD), timezone (SGT), exchange rate (1.36) — reads from brands/{brand}/brand.md Locale',
      'brand-setup: added Locale section to brand.md template (Currency, Timezone, Meta USD exchange rate)',
      'brand-setup: Step 4 website analysis now infers locale from TLD, address, phone country code, currency symbols',
      'brand-setup: funnel.md cost benchmarks reference brand.md currency instead of hardcoded SGD',
      'social-publisher: replaced hardcoded Asia/Singapore timezone and SGT publish times with brand timezone from brand.md',
      'content-generator: replaced hardcoded 09:00 SGT and TZ=Asia/Singapore with brand timezone from brand.md',
      'social-calendar: replaced hardcoded 09:00 SGT with cron schedule reference',
      'research-strategy: replaced hardcoded USD→SGD 1.357 CPC conversion with brand.md exchange rate',
      'data-analysis: replaced hardcoded SGD/1.36 currency conversion with brand.md Locale',
      'commit-to-git: replaced hardcoded 11PM SGT and TZ=Asia/Singapore with brand timezone',
      'fiveagents.io email/send/route.ts: template routing — tag-based renderer dispatch (paid-ads-daily/weekly → paid-ads-brief.ts)',
      'fiveagents.io email/send/route.ts: wrapInTemplate simplified to logo + footer only (no duplicate title)',
      'fiveagents.io: new lib/email/templates/paid-ads-brief.ts — server-side HTML renderer ported from Link render_brief.py',
      'fiveagents.io: new lib/email/templates/index.ts — template registry for future skill renderers',
    ],
  },
  {
    version: 'v2.1.5',
    date: 'April 10, 2026',
    changes: [
      'content-generator: gemini_generate_image returns JSON — parse image_base64 before passing to image_add_text_overlay',
      'content-generator: image_add_text_overlay returns JSON — parse image_base64 before passing to image_add_logo',
      'content-generator: image_add_logo returns JSON — parse image_base64 for upload',
      'content-generator: model updated to gemini-3.1-flash-image-preview',
      'content-generator: clarified image_base64 source for pre-stored vs generated backgrounds in Step 4d',
      'creative-designer: gemini_generate_image returns JSON — parse image_base64 for pipeline',
      'creative-designer: image_add_text_overlay and image_add_logo return JSON — parse between steps',
      'creative-designer: model updated to gemini-3.1-flash-image-preview',
      'creative-designer: added aspect_ratio param to gemini_generate_image call',
      'creative-designer: fixed duplicate Step 5 heading — Argil section renumbered to Step 6',
      'creative-designer: fixed day-of-week rotation label (bottom/top → always bottom)',
      'creative-designer: added No Python PIL fallback note',
      'background-generator: gemini_generate_image returns JSON — parse image_base64 to save file',
      'background-generator: model updated to gemini-3.1-flash-image-preview',
      'background-generator: fixed "Nano Banana" reference → Gemini in prompt rules',
      'background-generator: added No Python PIL fallback note',
    ],
  },
  {
    version: 'v2.1.4',
    date: 'April 10, 2026',
    changes: [
      'brand-setup: Step 4 switched from Claude in Chrome to Playwright MCP for website analysis',
      'brand-setup: improved browser_evaluate color selectors (h1, nav, a, button) — more reliable than body fallback',
      'brand-setup: added Cloudflare/blocked-site fallback note in Step 4',
      'brand-setup: Step 1 corrected MCP connectors reference from Step 2 to Step 7',
      'brand-setup: added Playwright to Step 2 prerequisites MCP table',
      'brand-setup: Step 5 GA4 event discovery now defers to Step 8 by default (Windsor.ai not yet set up)',
      'brand-setup: Step 7a removed incorrect "Claude Code users can skip connector" note',
      'brand-setup: added Playwright to Step 7c MCP connectors table',
      'brand-setup: added Playwright test (#10) and Canva test (#16) in Step 8 validation',
      'brand-setup: added Playwright to Step 8 summary table and report block',
      'brand-setup: added logo.png to Step 9 brand context files summary',
    ],
  },
  {
    version: 'v2.1.3',
    date: 'April 10, 2026',
    changes: [
      'brand-setup: added Windsor.ai free account signup as prerequisite (Step 2 and Step 7c)',
      'brand-setup: Step 7c Windsor.ai now walks user through all 3 steps (signup → connect ad accounts → authorize)',
      'brand-setup: added Canva to Step 2 prerequisites overview table',
      'brand-setup: added Canva to Step 8 validation summary table and report block',
    ],
  },
  {
    version: 'v2.1.2',
    date: 'April 10, 2026',
    changes: [
      'brand-setup: Claude in Chrome traverses homepage + all 1st-level navbar pages',
      'brand-setup: auto-detects primary/secondary colors and Google Fonts from computed styles',
      'brand-setup: Step 5 runs /research-strategy to fill product.md and competitors.md',
      'brand-setup: Step 6 is logo-only (fonts no longer asked separately)',
      'brand-setup: prerequisites no longer asks for colors/fonts (auto-detected in Step 4)',
      'brand-setup: fixed sub-step labels 7a/7b/7c and 8a/8b/8c',
      'brand-setup: removed fonts/ from folder structure (Google Fonts replaces local .ttf)',
    ],
  },
];
